export default [
  'This cabinet minister, does he always travel on the wrong side of the border?',
  'Cos some damn fool accused you of being the best.',
  'Dillon! You son of a bitch!',
  "What's the matter? The CIA got you pushing too many pencils?",
  'I heard about that job you pulled off in Berlin. Very nice, Dutch.',
  'General, my team always works alone. You know that.',
  "This stuff'll make you a goddamn sexual tyrannosaurus... just like me.",
  'Run... Go... Get to the chopper!',
  'Stick around.',
  "That's a real nasty habit you got there.",
  'If it bleeds, we can kill it.',
  "There's something out there waiting for us, and it ain't no man. We're all gonna die.",
  "Here we are again, bro... Just you and me. Same kind of moon, same kind of jungle. Real number 10, remember? Whole platoon, 32 men chopped into meat... We walk out, just you and me, nobody else. Right on top, bro. Not a scratch... Not a fuckin' scratch. You know, who ever got you, they'll come back again. And when he does, I'm gonna cut your name right into him... I'm gonna cut your name into him!",
  "You're ghostin' us, motherfucker. I don't care who you are back in the world, you give away our position one more time, I'll bleed ya, real quiet. Leave ya here. Got that?",
  "When I was little, we found a man. He looked like - like, butchered. The old women in the village crossed themselves, and whispered crazy things, strange things. 'El diablo cazador de hombres'. Only in the hottest years this happens. And this year, it grows hot. We begin finding our men. We found them sometimes without their skin... and sometimes much, much worst. 'El que hace trofeos de los hombres' means 'the demon who makes trophies of man'",
  'What happened to you, Dillon? You used to be someone I could trust.',
  'She says the jungle... it just came alive and took him.',
  "Long Tall Sally, she built sweet, she got everything, that Uncle John need. Aw baby, I'm gonna have me some fun, I'm gonna have me some fun, I'm gonna have me some fun.",
  'You set us up. It was bullshit, all of it.',
  'So you cooked up a story and dropped the six of us in a meatgrinder?',
  'I see you!',
  "Goddamn jackpot. This is more than we ever thought we'd get. We finally got those bastards. We got 'em.",
  "Time to let Ol' Painless out of the bag.",
  'Payback time.',
  'We move, five meter spread, no sound.',
  "You lose it here, you're in a world of hurt.",
  'Not a thing. Not a fucking trace. No blood, no bodies... We hit nothing!',
  "You still don't understand, Dillon, do you? Whatever it is out there, it killed Hopper, and now it wants us.",
  'So, what are you gonna try next? Cheese?',
  'Déme el arma. Déme el arma! Give me the weapon!',
  'Son of a bitch is dug in like an Alabama tick.',
  'Hey Billy, give me a way out of this hole. Aerial says we are cut off.',
  'Any time.',
  "He's busted up pretty bad, Major.",
  'Heat seeker, Dillon. Pretty sophisticated for a bunch of half-assed mountain boys.',
  'Good work, Mac. Clear the area. No traces.',
  'You got time to duck?',
  "We've been looking for this place for months. My men were in that chopper when it got hit!",
  "You're an asset. An expendable asset. And I used you to get the job done, got it?",
  "My men are not expendable. And I don't do this kind of work.",
  "The only way outta here is that valley that leads to the east. I wouldn't waste that on a broke-dick dog.",
  'Makes Cambodia look like Kansas.',
  "There's something in those trees.",
  "Major... you'd better take a look at this.",
  "Hold it! Why didn't they take his radio or his weapon? Why didn't she escape?",
  'Those eyes, they... they disappeared.',
  'I know one thing, Major. I drew and fired straight at it. Capped off 200 rounds in the Minigun... Full pack. Nothing... nothing on this earth could have lived. Not at that range.',
  'Do you think you could have found something bigger?',
  'It changed colours like the chameleon. It uses the jungle.',
  'There is something else. When the big man was killed, you must have wounded it. Its blood was on the leaves.',
]
