const predQuotes = [
  {"quote": "This cabinet minister, does he always travel on the wrong side of the border?", "character": "Dutch"},
  {"quote": "Cos some damn fool accused you of being the best.", "character": "Dillon"},
  {"quote": "What's the matter? The CIA got you pushing too many pencils?", "character": "Dutch"},
  {"quote": "I heard about that job you pulled off in Berlin. Very nice, Dutch.", "character": "Dillon"},
  {"quote": "General, my team always works alone. You know that.", "character": "Dutch"},
  {"quote": "This stuff'll make you a goddamn sexual tyrannosaurus... just like me.", "character": "Blain"},
  {"quote": "Run... Go... Get to the chopper!", "character": "Dutch"},
  {"quote": "Stick around.", "character": "Dutch"},
  {"quote": "That's a real nasty habit you got there.", "character": "Dillon"},
  {"quote": "If it bleeds, we can kill it.", "character": "Dutch"},
  {"quote": "There's something out there waiting for us, and it ain't no man. We're all gonna die.", "character": "Billy"},
  {"quote": "When I was little, we found a man. He looked like - like, butchered. The old women in the village crossed themselves, and whispered crazy things, strange things. 'El diablo cazador de hombres'. Only in the hottest years this happens. And this year, it grows hot. We begin finding our men. We found them sometimes without their skin... and sometimes much, much worst. 'El que hace trofeos de los hombres' means 'the demon who makes trophies of man'", "character": "Anna"},
  {"quote": "What happened to you, Dillon? You used to be someone I could trust.", "character": "Dutch"},
  {"quote": "She says the jungle... it just came alive and took him.", "character": "Poncho"},
  {"quote": "Long Tall Sally, she built sweet, she got everything, that Uncle John need. Aw baby, I'm gonna have me some fun, I'm gonna have me some fun, I'm gonna have me some fun.", "character": "Mac"},
  {"quote": "So you cooked up a story and dropped the six of us in a meatgrinder?", "character": "Dutch"},
  {"quote": "I see you!", "character": "Mac"},
  {"quote": "Goddamn jackpot. This is more than we ever thought we'd get. We finally got those bastards. We got 'em.", "character": "Dillon"},
  {"quote": "Time to let Ol' Painless out of the bag.", "character": "Mac"},
  {"quote": "Payback time.", "character": "Blain"},
  {"quote": "We move, five meter spread, no sound.", "character": "Dutch"},
  {"quote": "You lose it here, you're in a world of hurt.", "character": "Blain"},
  {"quote": "You still don't understand, Dillon, do you? Whatever it is out there, it killed Hopper, and now it wants us.", "character": "Dutch"},
  {"quote": "So, what are you gonna try next? Cheese?", "character": "Dillon"},
  {"quote": "Déme el arma. Déme el arma! Give me the weapon!", "character": "Anna"},
  {"quote": "Hey Billy, give me a way out of this hole. Aerial says we are cut off.", "character": "Dutch"},
  {"quote": "Any time.", "character": "Mac"},
  {"quote": "He's busted up pretty bad, Major.", "character": "Billy"},
  {"quote": "Heat seeker, Dillon. Pretty sophisticated for a bunch of half-assed mountain boys.", "character": "Dutch"},
  {"quote": "Good work, Mac. Clear the area. No traces.", "character": "Dutch"},
  {"quote": "You got time to duck?", "character": "Poncho"},
  {"quote": "We've been looking for this place for months. My men were in that chopper when it got hit!", "character": "Dillon"},
  {"quote": "You're an asset. An expendable asset. And I used you to get the job done, got it?", "character": "Dillon"},
  {"quote": "My men are not expendable. And I don't do this kind of work.", "character": "Dutch"},
  {"quote": "The only way outta here is that valley that leads to the east. I wouldn't waste that on a broke-dick dog.", "character": "Billy"},
  {"quote": "Makes Cambodia look like Kansas.", "character": "Blain"},
  {"quote": "There's something in those trees.", "character": "Billy"},
  {"quote": "Major... you'd better take a look at this.", "character": "Poncho"},
  {"quote": "Hold it! Why didn't they take his radio or his weapon? Why didn't she escape?", "character": "Dutch"},
  {"quote": "Those eyes, they... they disappeared.", "character": "Mac"},
  {"quote": "I know one thing, Major. I drew and fired straight at it. Capped off 200 rounds in the Minigun... Full pack. Nothing... nothing on this earth could have lived. Not at that range.", "character": "Mac"},
  {"quote": "Do you think you could have found something bigger?", "character": "Poncho"},
  {"quote": "It changed colours like the chameleon. It uses the jungle.", "character": "Anna"},
  {"quote": "There is something else. When the big man was killed, you must have wounded it. Its blood was on the leaves.", "character": "Anna"}
]

module.exports = predQuotes
